
-- UPFEST CONTROL - SCRIPT DE ESTRUCTURA Y SEGURIDAD v5 (NUEVA CUENTA)
-- Ejecutar en el SQL Editor del NUEVO proyecto.

-- 1. Tablas principales
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  dni TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT DEFAULT 'Mozo',
  legajo TEXT,
  dress_code TEXT,
  reference_image TEXT,
  schedule JSONB DEFAULT '[]',
  assigned_locations JSONB DEFAULT '[]',
  email TEXT,
  phone TEXT,
  address TEXT,
  is_active BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  radius_meters INTEGER DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  legajo TEXT,
  timestamp TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL,
  location_id TEXT,
  location_name TEXT,
  location_status TEXT,
  schedule_status TEXT,
  dress_code_status TEXT,
  identity_status TEXT,
  photo_evidence TEXT,
  ai_feedback TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Activar Seguridad RLS (Para evitar el error del mail)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.app_settings ENABLE ROW LEVEL SECURITY;

-- 3. Políticas de Acceso (Permitir a la App operar)
CREATE POLICY "Permitir todo a usuarios anon" ON public.users FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a sedes anon" ON public.locations FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a logs anon" ON public.logs FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Permitir todo a settings anon" ON public.app_settings FOR ALL USING (true) WITH CHECK (true);

-- 4. Recargar esquema
NOTIFY pgrst, 'reload schema';
