
-- UPFEST CONTROL - SCRIPT DE ACTUALIZACIÓN DE BASE DE DATOS DEFINITIVO

-- 1. Forzar la creación de columnas faltantes en la tabla 'users'
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS assigned_locations JSONB DEFAULT '[]';

-- 2. Asegurar que el resto de las tablas existan
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  radius_meters INTEGER DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  legajo TEXT,
  timestamp TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL,
  location_id TEXT,
  location_name TEXT,
  location_status TEXT,
  schedule_status TEXT,
  dress_code_status TEXT,
  identity_status TEXT,
  photo_evidence TEXT,
  ai_feedback TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- INSTRUCCIONES:
-- 1. Copia todo este código.
-- 2. Ve a tu proyecto de Supabase -> SQL Editor -> New Query.
-- 3. Pega el código y dale a "RUN".
-- 4. Si el error persiste en la app, espera 30 segundos y recarga la página (F5) para que Supabase refresque el caché.
