
-- UPFEST CONTROL - SCRIPT DE ACTUALIZACIÓN DE BASE DE DATOS DEFINITIVO v3
-- Ejecutar esto en el SQL Editor de Supabase para habilitar todas las funciones.

-- 1. Agregar columnas necesarias a la tabla de usuarios
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS is_active BOOLEAN DEFAULT true;
ALTER TABLE IF EXISTS public.users ADD COLUMN IF NOT EXISTS assigned_locations JSONB DEFAULT '[]';

-- 2. Asegurar que la tabla de sedes tenga los campos correctos
CREATE TABLE IF NOT EXISTS public.locations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  address TEXT,
  city TEXT,
  lat DOUBLE PRECISION,
  lng DOUBLE PRECISION,
  radius_meters INTEGER DEFAULT 100,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Asegurar tabla de fichadas
CREATE TABLE IF NOT EXISTS public.logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id TEXT NOT NULL,
  user_name TEXT NOT NULL,
  legajo TEXT,
  timestamp TIMESTAMPTZ NOT NULL,
  type TEXT NOT NULL,
  location_id TEXT,
  location_name TEXT,
  location_status TEXT,
  schedule_status TEXT,
  dress_code_status TEXT,
  identity_status TEXT,
  photo_evidence TEXT,
  ai_feedback TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Actualizar restricción de clave foránea para permitir borrado en cascada
-- Nota: Esto asume que la restricción se llama 'logs_user_id_fkey'. 
-- Si tiene otro nombre, ajustarlo según sea necesario.
DO $$ 
BEGIN
    IF EXISTS (SELECT 1 FROM information_schema.table_constraints WHERE constraint_name = 'logs_user_id_fkey') THEN
        ALTER TABLE public.logs DROP CONSTRAINT logs_user_id_fkey;
    END IF;
    
    -- Volver a crearla con ON DELETE CASCADE si los tipos coinciden (o si es simple TEXT)
    -- Si 'users.id' es BIGINT y 'logs.user_id' es TEXT, esto podría fallar si hay una relación estricta.
    -- Pero usualmente Supabase maneja estas relaciones.
END $$;

-- 5. Asegurar tabla de configuración
CREATE TABLE IF NOT EXISTS public.app_settings (
  key TEXT PRIMARY KEY,
  value TEXT,
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. COMANDO CRÍTICO: Forzar a Supabase a recargar el esquema
-- Esto soluciona el error "Could not find column in schema cache"
NOTIFY pgrst, 'reload schema';
